#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  local url_maven='http://www-us.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz'
  local fnm_maven='apache-maven-3.3.9-bin.tar.gz'

  cache curl "$fnm_maven" "$url_maven"

  mkdir -p "$shome/vendor"
  (cd "$shome/vendor" && tar xvfz "${BASEBOX_CACHE}/curl/$fnm_maven")
  (cd "$shome/vendor" && ln -nfs "apache-maven-3.3.9" "maven")
}

bootstrap
