#!/usr/bin/env bash

function _maven_profile {
  local shome="${_maven_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/vendor/maven/bin:$PATH"
}

_maven_profile
